In [1]:
import numpy as np

stock = np.array(['Birlasoft','Tech Mahindra','Tata Elsxi','Tata Chemical','SAIL','SPEL','Info Edge','Tata Power'])
np.split(stock,2)

[array(['Birlasoft', 'Tech Mahindra', 'Tata Elsxi', 'Tata Chemical'],
       dtype='<U13'),
 array(['SAIL', 'SPEL', 'Info Edge', 'Tata Power'], dtype='<U13')]

In [2]:
np.hsplit(stock,2)

[array(['Birlasoft', 'Tech Mahindra', 'Tata Elsxi', 'Tata Chemical'],
       dtype='<U13'),
 array(['SAIL', 'SPEL', 'Info Edge', 'Tata Power'], dtype='<U13')]

In [3]:
print(2)

2


In [4]:
List1 = [5, 50, 55, 555, 5555]

A=List1.count(5)
A

1

In [5]:
s = ''\t\t\t\n\nTutorialsPoint\n\n\n\t\t\t''
X=s.strip()
X

SyntaxError: unexpected character after line continuation character (<ipython-input-5-b2b1bf2edca7>, line 1)

In [ ]:
q = 'vwxyz'
for i in range(len(q)):
   print(q)
   q = 'v'

Sum of cummulative numbers

In [ ]:
x1=[10,20,30,40,50]
total=0
b=[]
for i in range(len(x1)):
    total=total+x1[i]
    b.append(total)
b

sum of N natural numbers

In [ ]:
total=0
for i in range(10):
    print(i)
    total=total+i
print(total)
    

In [ ]:
w1="Don't mess with a Lazy Boy"
w1.count('l')

In [ ]:

f1=w1.count('s')
f1

In [ ]:
marks =[25,50,75,45,92,75, 78,75]
marks.count(3)

In [ ]:
import re
w1="Don't mess with a Lazy Boyz 34"
exp=re.search('z',w1)
print(exp)

In [ ]:
exp=re.search(r'tt',w1)
print(exp)

In [ ]:
import re
w1="Don't mess with a Lazy Boy"
exp=re.search('z',w1)
exp
if exp != None:
    print('Found a Match')
else:
    print('Match is not found')

In [ ]:
regex = r"[a-zA-Z]+\s+\d+"
  
exp1 = re.search(regex, "I was born on June 24") 
exp1

In [ ]:
exp1.start(),exp1.end(),exp1.group(0)

In [ ]:
print ("Match at index :", match.start(),"," ,match.end())
print ("Full match:",match.group(0))

In [ ]:
# A Python program to demonstrate working of re.match().
import re

# Lets use a regular expression to match a date string
# in the form of Month name followed by day number
regex = r"([a-zA-Z]+) (\d+)"

match = re.search(regex, "I was born on June 24")

if match != None:

	# We reach here when the expression "([a-zA-Z]+) (\d+)"
	# matches the date string.

	# This will print [14, 21), since it matches at index 14
	# and ends at 21.
	print ("Match at index %s, %s" % (match.start(), match.end()))

	# We us group() method to get all the matches and
	# captured groups. The groups contain the matched values.
	# In particular:
	# match.group(0) always returns the fully matched string
	# match.group(1) match.group(2), ... return the capture
	# groups in order from left to right in the input string
	# match.group() is equivalent to match.group(0)

	# So this will print "June 24"
	print ("Full match: %s" % (match.group(0)))

	# So this will print "June"
	print ("Month: %s" % (match.group(1)))

	# So this will print "24"
	print ("Day: %s" % (match.group(2)))

else:
	print ("The regex pattern does not match.")


In [ ]:
from platform import python_version
print(python_version())

Learn through Upgrad `Because it is has partnered with IIIT B` so Enjoy
there are following benefit to do **PG Program** via upgrad:
-  get a cerficate from IIIT B
-  get hired by high paying job company

Split the string input_str = 'Kumar_Ravi_003' to the person's second name, first name and unique customer code. 
In this example, second_name= 'Kumar', first_name= 'Ravi', customer_code = '003'.

In [ ]:
import ast,sys
input_str =  'Kumar_Ravi_003' 
first_name = input_str[6:10]
second_name = input_str[0:5]
customer_code = input_str[-3:]
print(first_name)
print(second_name)
print(customer_code)

In [ ]:
len('Python')

In [ ]:
input_str =  'Kumar_Ravi_003' 
input_str=input_str.split('_')
input_str

In [ ]:
first_name = input_str[1]
second_name = input_str[0]
customer_code = input_str[-1]
print(first_name)
print(second_name)
print(customer_code)

In [ ]:
type(first_name)

In [ ]:
stocks=['Birlasoft','Tech Mahindra','Tata Elsxi','Tata Chemical','SAIL','SPEL','Info Edge','Tata Power']

In [ ]:
stocks.append('MOSCHIP')
stocks

In [ ]:
len(stocks)

In [ ]:
stocks[len(stocks):] = ['BANK BEES']
stocks

In [ ]:
stocks.insert(3,'HSCL')
stocks

In [ ]:
stocks.insert(9,'SPEL')
stocks

In [ ]:
#List Casting
#If word = ['1','2','3','4'], what will be the output of the following code?
word = ['1','2','3','4']
word[ : ] = ['Shrawan'] 
print(word)

In [ ]:
str1= [1, 2, 3, 4, 5]
str2 = [6, 7, 8, 9]
str1

In [ ]:
str2

First, convert the lists into sets and store them as set_1 and set_2.
Then store the difference and symmetric difference in answer_1 and answer_2 respectively. 
Print both the answers as sorted lists, i.e. convert the final sets to lists, sort it and then return it.

In [ ]:
str1.extend(str2)
str1

In [ ]:
import ast,sys
input_str = sys.stdin.read()
input_list = [[1,2,3,4,5,6],[2,3,4,5,6,7,8,9]]
list_1 = input_list[0]
list_2 = input_list[1]

set_1 = set(list_1)
set_2 = set(list_2)
set_1,set_2

In [ ]:
difference1=set_1.difference(set_2)
difference1

In [ ]:
difference2=set_2.difference(set_1)
difference2

In [ ]:
symemetric_difference=difference1.union(difference2)
symemetric_difference

In [ ]:
difference=list(difference1)
difference

In [ ]:
symemetric_difference=list(symemetric_difference)
symemetric_difference

In [ ]:
symemetric_difference=sorted(symemetric_difference)
symemetric_difference

In [ ]:
answer_1 = list(set_1.difference(set_2))
symmetric_difference = answer_1.union(set_2.difference(set_1))
answer_2 = list(symmetric_difference)
answer_2 =sorted(answer_2)

print(answer_1)
print(answer_2)

In [ ]:
import ast,sys
input_str = 'alpha'

if input_str[0]=='a'or 'e'or'i'or 'o'or 'u':
    print('YES')
else:
    print('NO')
    

In [ ]:
input_str = 'alpha'
if input_str[0] in ['a','e','i','o','u']:
    print('YES')
else:
    print('NO')

In [ ]:
for i in range(100):
    print(i)
    if i>5:
        break
        print("Hello")

In [ ]:
#Using the following document answer the following questions.
#What will the output of the following be?
d = {0: 'Fish', 1: 'Bird', 2: 'Mammal'}
for i in d:
    print(i)

In [ ]:
d = {0, 1, 2}
for x in d:
    print(d.add(x))
    

In [ ]:
for i in range(1,6):
    if (i % 3 == 0):
        print(str(i) + " is Divisible by 3")
        break

    print(str(i) + " is not divisible by 3")

In [ ]:
for i in range(1,6):
    if (i % 3 == 0):
        print(str(i) + " is Divisible by 3")
        continue

    print(str(i) + " is not divisible by 3")

In [ ]:
for i in range(1,6):
    if (i % 3 == 0):
        print(str(i) + " is Divisible by 3")
        pass

    print(str(i) + " is not divisible by 3")

In [ ]:
#Extract the words that start with a vowel from a list
#using list comprehensions.

In [ ]:
input_list=['wood', 'old', 'apple', 'big', 'item', 'euphoria']
for word in input_list:
    if word[0] in ['a','e','i','o','u']:
        print(word)

In [ ]:
input_list.split()

In [ ]:
input_list=['wood', 'old', 'apple', 'big', 'item', 'euphoria'] 
vowels=['a','e','i','o','u']
word=[word for word in input_list if word[0] in vowels]
word

In [ ]:
print([i+j for i in "abc" for j in "def"])
 

In [ ]:
d = {x.upper(): x*3 for x in 'acbd'}
print(d)

In [ ]:
def factorial(n):
    if n>1:
        fact=n*factorial(n-1)
        return(fact)
    else:
        return(n)
print(factorial(5))

In [ ]:
t1=(4,5,6,7,8,9)
x=0
for i in t1:
    print(i)
    x=x+i
print(x)
    

In [ ]:
captain="mahendra singh dhoni"
def capitalize(captain):
    captain_name=" ".join([word[0].upper()+word[1:] for word in captain.split()])
    return(captain_name)
print(capitalize(captain))

In [ ]:
string_to_list= lambda x:x.split()
print(string_to_list(captain))

In [ ]:
def say(message, times = 1):
    print(message * times)

say('Hello')
say('World', 5)

In [ ]:
min = (lambda x, y: x if x < y else y)
min(101*99, 102*98)

In [ ]:
#Map Function
#Description
#Using the function Map, count the number of words that start with ‘S’ in input_list.
str1='S'
input_list=['San Jose', 'San Francisco', 'Santa Fe', 'Houston']
count= list(map(lambda x: x[0], input_list))
count
x1=0
for char in count:
    if char=='S':
        x1=x1+1
print(x1)

In [ ]:
input_list=['San Jose', 'San Francisco', 'Santa Fe', 'Houston']
count=0
for x in input_list:
    if x[0][0]=='S':
        print(x[0])
        count =count+1
print(count)

**MAP FUNCCTION**

In [ ]:
def fahrenheit(T):
    return ((float(9)/5)*T + 32)
def celsius(T):
    return (float(5)/9)*(T-32)
temp_in_celsius = (36.5, 37, 37.5,39)
F = list(map(fahrenheit, temp))
print(F)

In [ ]:
input_list=[ ['Ankur', 'Avik', 'Kiran', 'Nitin'], ['Narang', 'Sarkar', 'R', 'Sareen']]
first_name = input_list[0]
last_name = input_list[1]
name = list(map(lambda x,y:x+" "+y, first_name,last_name))
print(name)

**Reduce Function**

In [ ]:

input_list = ['All','you','have','to','fear','is','fear','itself']

from functools import reduce

feelings =reduce(lambda x, y: x+ ' '+y, input_list)

print(feelings)

In [ ]:
x1=((500//7) % 5) ** 3
x1

In [ ]:
2*[1,2,3]

In [ ]:
 L = [[1, 2, 3], [4, 5, 6], [7, 8, 9, 10]]
L[2:]

In [ ]:
 T = (3, 5, 7, 11)
T.append(9)

In [ ]:
D = {1:['Raj', 22], 2:['Simran', 21], 3:['Rahul', 40]}
for val in D:
     print(val)

In [ ]:
def my_func(*args):
    return(sum(args))

print(my_func(1,2,3,4,5))
print(my_func(6,7,8))

In [ ]:
n = int(input())

# Import the reduce() function
from functools import reduce
fact=0
def factorial(n):
    if n == 0:
        return 1
    else:
        fact = reduce(lambda x,y: x*y, range(1,n+1))
        return(fact)

                      
print(factorial(n))

In [ ]:
import functools
n = int(input())

def factorial(n):
    if n == 0:
        return 1
    else:
        return functools.reduce(lambda x,y: x*y, range(1,n+1))

print(factorial(n))

Description
In a school, there are total 20 students numbered from 1 to 20. You’re given three lists named ‘C’, ‘F’, and ‘H’, representing students who play cricket, football, and hockey, respectively. Based on this information, find out and print the following: 
Students who play all the three sports
Students who play both cricket and football but don’t play hockey
Students who play exactly two of the sports
Students who don’t play any of the three sports
Format:
Input:
3 lists containing numbers (ranging from 1 to 20) representing students who play cricket, football and hockey respectively.
Output:
4 different lists containing the students according to the constraints provided in the questions.

Note: Make sure you sort the final lists (in an ascending order) that you get before printing them; otherwise your answer might not match the test-cases.

Examples:
Input 1:
[2, 5, 9, 12, 13, 15, 16, 17, 18, 19]
[2, 4, 5, 6, 7, 9, 13, 16]
[1, 2, 5, 9, 10, 11, 12, 13, 15]
Output 1:
[2, 5, 9, 13]
[16]
[12, 15, 16]
[3, 8, 14, 20]

Explanation:
1.Given the three sets, you can see that the students numbered '2', '5', '9', and '13' play all the three sports. 
2. The student numbered '16' plays cricket and football but doesn't play hockey. 
3. The student numbered '12' and '15' plays cricket and hockey and the student numbered '16' plays cricket and football. There are no students who play only football and hockey. Hence, the students who play exactly two sports are 12, 15, and 16.
4. As you can see, the students who play none of the sports are 3, 8, 14, and 20.

In [ ]:
C={2, 5, 9, 12, 13, 15, 16, 17, 18, 19}
F={2, 4, 5, 6, 7, 9, 13, 16}
H= {1, 2, 5, 9, 10, 11, 12, 13, 15}

ALL= set(range(1, 21))
play_all1=C&F&H

cf_lover2=(C&F)-(H)

exactly_two3=((C-F)&H | (C-H)&F)

not_interested4= (ALL-(C|F|H))

play_all =list(play_all1)
play_all = sorted(play_all)
print(play_all)

cf_lover2=list(cf_lover2)
cf_lover2=sorted(cf_lover2)
print(cf_lover2)

exactly_two=list(exactly_two3)
exactly_two=sorted(exactly_two)
print(exactly_two)

not_interested=list(not_interested4)
not_interested=sorted(not_interested)
print(not_interested) 

In [ ]:
# Read the three input lists, i.e. 'C', 'F', and 'H'.
input_list=[[2, 5, 9, 12, 13, 15, 16, 17, 18, 19], [2, 4, 5, 6, 7, 9, 13, 16], [1, 2, 5, 9, 10, 11, 12, 13, 15]]

C = input_list[0]
F = input_list[1]
H = input_list[2]

C= set(C)
F= set(F)
H = set(H)
all_set=C|F|H
#ALL= len(all_set)
ALL= set(range(1, len(all_set)+5))
play_all1=C&F&H

cf_lover2=(C&F)-(H)

exactly_two3=((C-F)&H | (C-H)&F)

not_interested4= ALL-(C|F|H)

play_all =list(play_all1)
play_all = sorted(play_all)
print(play_all)

cf_lover2=list(cf_lover2)
cf_lover2=sorted(cf_lover2)
print(cf_lover2)

exactly_two=list(exactly_two3)
exactly_two=sorted(exactly_two)
print(exactly_two)

not_interested=list(not_interested4)
not_interested=sorted(not_interested)
print(not_interested) 


In [ ]:
all_set=C|F|H
all_set

In [ ]:
ALL

In [ ]:
len(all_set)

In [ ]:
y1=[1,2,3,4,5]
for x in range(0, len(y1)):
    print(x)

In [ ]:
len(y1)

**Numpy**

In [ ]:
import numpy as np
g1=[[2, 5, 9], [2, 4, 5], [1, 2, 5]]

g11=g1[0]
g22=g1[1]
g33=g1[2]

len(g11),len(g22),len(g33)


In [ ]:
p=np.array(g11)
q=np.array(g22)
r=np.array(g33)
print(p)
print(q)
print(r)
array_result=p*q*r
print(type(array_result))
print(array_result)
print(list(p*q*r))

In [ ]:
distance =[10,15,17,26]
np_distance=np.array(distance)
np_distance

In [ ]:
import numpy as np
g11=[2, 5, 9,54]
g22=[2, 4, 5,87]
g33=[1, 2, 5,44]

len(g11),len(g22),len(g33)

In [ ]:
p=np.array(g11)
q=np.array(g22)
r=np.array(g33)
print(p)
print(q)
print(r)
array_result=p*q*r
print(type(array_result))
print(array_result)
print(list(p*q*r))

In [ ]:
np.ones(5)

In [ ]:
np.zeros(6)

In [ ]:
np.random.random(4)

In [ ]:
np.arange(10)

In [ ]:
np.linspace(2,8)

In [ ]:
array_ones=np.ones(((2,3,4)))
print(array_ones.ndim)
array_ones

In [ ]:
np.full((5,4),3)

In [ ]:
np.arange(15,750,3)

np.full(): Create a constant array of any number ‘n’

In [5]:
import numpy as np
a1=np.full((5,4),2)
a1

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [ ]:
a2=np.full((3,4,5),6)
a2

np.tile(): Create a new array — by repeating an existing array — for a particular number of times

In [6]:
a3=np.tile(a1,3)
a3

array([[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]])

**np.eye()**: Create an identity matrix of any dimension

In [ ]:
np.eye(2,5)

**np.randint()**: Create a random array of integers within a particular range

In [ ]:
np.randint()

Checkerboard Matrix
Description
Given an even integer ‘n’, create an ‘n*n’ checkerboard matrix with the values 0 and 1, using the tile function.
 
Format:
Input: A single even integer 'n'.
Output: An 'n*n' NumPy array in checkerboard format.

Example:
Input 1:
2
Output 1:
[[0 1]
 [1 0]]
Input 2:
4
Output 2:
[[0 1 0 1] 
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]]

Execution Time Limit

In [7]:
a1=np.array([[0,1],[1,0]])
a1

array([[0, 1],
       [1, 0]])

In [8]:
n = int(input())
np.tile(a1,n)

4


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [10]:
n = int(input())
t3=np.tile(a1,(int(n/2),int(n/2)))
t3

4


array([[0, 1, 0, 1],
       [1, 0, 1, 0],
       [0, 1, 0, 1],
       [1, 0, 1, 0]])

In [16]:
t3.reshape(n,4)

array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [1, 0, 1, 0],
       [1, 0, 1, 0]])

In [29]:
input_list=np.array([[2, 5, 9, 12, 13, 15, 16, 17], [2, 4, 5, 6, 7, 9, 13, 16], [1, 2, 5, 9, 10, 11, 12, 13]])

input_list

array([[ 2,  5,  9, 12, 13, 15, 16, 17],
       [ 2,  4,  5,  6,  7,  9, 13, 16],
       [ 1,  2,  5,  9, 10, 11, 12, 13]])

In [31]:
input_list.shape

(3, 8)

In [32]:
input_list[1]

array([ 2,  4,  5,  6,  7,  9, 13, 16])

In [33]:
rand_array=np.random.random((1000,300))
rand_array

array([[0.33601861, 0.94225485, 0.53958987, ..., 0.55191861, 0.79870709,
        0.53407327],
       [0.35232478, 0.15880152, 0.27384572, ..., 0.98064834, 0.28760246,
        0.55049006],
       [0.56959319, 0.49776841, 0.55502282, ..., 0.11607671, 0.74391543,
        0.76232051],
       ...,
       [0.56491451, 0.74197601, 0.19217627, ..., 0.93199271, 0.14620556,
        0.73859528],
       [0.0022982 , 0.97363269, 0.15079999, ..., 0.12706472, 0.52937204,
        0.48970879],
       [0.43411196, 0.92236701, 0.06893169, ..., 0.11405261, 0.41095963,
        0.47618364]])

In [34]:
rand_array[1]

array([0.35232478, 0.15880152, 0.27384572, 0.31937303, 0.28118552,
       0.98163861, 0.30137841, 0.8198244 , 0.82292319, 0.7876989 ,
       0.19082724, 0.4403332 , 0.23915825, 0.98821785, 0.77717529,
       0.44352277, 0.31804351, 0.2924765 , 0.26153206, 0.20067981,
       0.96602762, 0.61145298, 0.75356738, 0.18608034, 0.24246077,
       0.23682921, 0.19070961, 0.01077235, 0.76602229, 0.04979345,
       0.2876919 , 0.80603393, 0.95752977, 0.27205305, 0.71766803,
       0.24308774, 0.8720702 , 0.81586034, 0.49559554, 0.07616034,
       0.56309689, 0.92186603, 0.57988891, 0.51309182, 0.29548557,
       0.30813499, 0.65767811, 0.36129649, 0.69609595, 0.70105276,
       0.73453748, 0.59528094, 0.71566092, 0.54416746, 0.43717194,
       0.82039229, 0.22828724, 0.57131644, 0.56615575, 0.37853616,
       0.36798249, 0.09051381, 0.06166258, 0.63203725, 0.19793602,
       0.00424258, 0.81032675, 0.01533723, 0.97559488, 0.93683798,
       0.27629652, 0.11245555, 0.46990449, 0.93971736, 0.41857

In [35]:
len(rand_array[1])

300

In [36]:
rand_array[1,]

array([0.35232478, 0.15880152, 0.27384572, 0.31937303, 0.28118552,
       0.98163861, 0.30137841, 0.8198244 , 0.82292319, 0.7876989 ,
       0.19082724, 0.4403332 , 0.23915825, 0.98821785, 0.77717529,
       0.44352277, 0.31804351, 0.2924765 , 0.26153206, 0.20067981,
       0.96602762, 0.61145298, 0.75356738, 0.18608034, 0.24246077,
       0.23682921, 0.19070961, 0.01077235, 0.76602229, 0.04979345,
       0.2876919 , 0.80603393, 0.95752977, 0.27205305, 0.71766803,
       0.24308774, 0.8720702 , 0.81586034, 0.49559554, 0.07616034,
       0.56309689, 0.92186603, 0.57988891, 0.51309182, 0.29548557,
       0.30813499, 0.65767811, 0.36129649, 0.69609595, 0.70105276,
       0.73453748, 0.59528094, 0.71566092, 0.54416746, 0.43717194,
       0.82039229, 0.22828724, 0.57131644, 0.56615575, 0.37853616,
       0.36798249, 0.09051381, 0.06166258, 0.63203725, 0.19793602,
       0.00424258, 0.81032675, 0.01533723, 0.97559488, 0.93683798,
       0.27629652, 0.11245555, 0.46990449, 0.93971736, 0.41857

In [37]:
np.arange(24)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [65]:
array_3d=np.arange(24).reshape(2,3,4)
array_3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [67]:
for col in array_3d:
    print(col)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [42]:
array_3d=np.arange(24).reshape(3,4,2)
array_3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [43]:
a1=np.arange(52,75,2)
a1

array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74])

In [49]:
a1[2,5,6]

IndexError: too many indices for array

In [50]:
a1[[2,5,6]]

array([56, 62, 64])

In [51]:
input_list=np.array([[2, 5, 9, 12, 13, 15, 16, 17], [2, 4, 5, 6, 7, 9, 13, 16], [1, 2, 5, 9, 10, 11, 12, 13]])

input_list

array([[ 2,  5,  9, 12, 13, 15, 16, 17],
       [ 2,  4,  5,  6,  7,  9, 13, 16],
       [ 1,  2,  5,  9, 10, 11, 12, 13]])

In [62]:
input_list[2]

array([ 1,  2,  5,  9, 10, 11, 12, 13])

In [64]:
input_list[2,2]

5

In [60]:
input_list[:2]

array([[ 2,  5,  9, 12, 13, 15, 16, 17],
       [ 2,  4,  5,  6,  7,  9, 13, 16]])

In [61]:
input_list[:,2]

array([9, 5, 5])

In [68]:
angle=np.arange(0,181,30)
angle

array([  0,  30,  60,  90, 120, 150, 180])

In [70]:
print(np.sin(angle))
print(np.cos(angle))

[ 0.         -0.98803162 -0.30481062  0.89399666  0.58061118 -0.71487643
 -0.80115264]
[ 1.          0.15425145 -0.95241298 -0.44807362  0.81418097  0.69925081
 -0.59846007]


In [71]:
input_list=[[1,2,3,4],[4,7,5,6],[9,0,7,8],[6,7,8,5]]
list_1 = input_list[0:2]
list_2 = input_list[2:4]
list_1

[[1, 2, 3, 4], [4, 7, 5, 6]]

In [72]:
list_2

[[9, 0, 7, 8], [6, 7, 8, 5]]

In [73]:
array_1 = np.array(list_1)
array_2 = np.array(list_2)
array_3 =np.hstack((array_1,array_2))
array_3

array([[1, 2, 3, 4, 9, 0, 7, 8],
       [4, 7, 5, 6, 6, 7, 8, 5]])

In [74]:
a1=np.linspace(2,12,4).reshape(2,2)
a1

array([[ 2.        ,  5.33333333],
       [ 8.66666667, 12.        ]])

In [75]:
a1=np.arange(2,9,2).reshape(2,2)
a1

array([[2, 4],
       [6, 8]])

In [76]:
a2=np.arange(1,8,2).reshape(2,2)
a2

array([[1, 3],
       [5, 7]])

In [77]:
a3=np.dot(a1,a2)
a3

array([[22, 34],
       [46, 74]])

**PANDAS**

In [81]:
import numpy as np
import pandas as pd
series_1 = pd.Series( [6,7,8,9,2,3,4,5] )
series_2 = series_1.apply(lambda x:x**2)
print(series_1)
print(series_2)

0    6
1    7
2    8
3    9
4    2
5    3
6    4
7    5
dtype: int64
0    36
1    49
2    64
3    81
4     4
5     9
6    16
7    25
dtype: int64


In [85]:
import pandas as pd
df=pd.read_csv("https://query.data.world/s/vBDCsoHCytUSLKkLvq851k2b8JOCkF")
print(df.head())
print(df.describe())
print(df.columns)
print(df.shape)

   X  Y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area
0  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0
1  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0
2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0
3  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0
4  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0
                X           Y        FFMC         DMC          DC         ISI  \
count  517.000000  517.000000  517.000000  517.000000  517.000000  517.000000   
mean     4.669246    4.299807   90.644681  110.872340  547.940039    9.021663   
std      2.313778    1.229900    5.520111   64.046482  248.066192    4.559477   
min      1.000000    2.000000   18.700000    1.100000    7.900000    0.000000   
25%      3.000000    4.000000   90.200000   68.600000  437.700000    6.500000   
50%      4.000000    4.000000   91.600000  108.300000  664.200000    8.400000   
75%    

Manual Indexing
Description
Create a panda series that contains the first ‘n’ natural numbers and their respective squares. The first ‘n’ numbers should appear in the index position.
Hint: Use manual indexing.
 
Format:
Input: A natural number 'n'
Output: A pandas series with the first 'n' natural numbers in the index position and their respective squares in the adjacent column.

Example:
Input 1:
4
Output 1:
1  1 
2  4 
3  9 
4  16 
dtype: int64

In [89]:
n = int(input())

import numpy as np 
import pandas as pd 
natual_numbers=np.arange(1,n+1)
s1=pd.Series(np.arange(1,n+1),index=natual_numbers)
output=s1.apply(lambda x:x**2)
print(output)

21
1       1
2       4
3       9
4      16
5      25
6      36
7      49
8      64
9      81
10    100
11    121
12    144
13    169
14    196
15    225
16    256
17    289
18    324
19    361
20    400
21    441
dtype: int64


Set Index in Dataframe
Description
Using set_index command set the column 'X' as the index of the dataset and then print the head of the dataset.
Hint: Use inplace = False 

In [1]:
import pandas as pd
df = pd.read_csv('https://query.data.world/s/vBDCsoHCytUSLKkLvq851k2b8JOCkF')
print(df.head())

   X  Y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area
0  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0
1  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0
2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0
3  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0
4  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0


In [3]:
df.iloc[3]

X           8
Y           6
month     mar
day       fri
FFMC     91.7
DMC      33.3
DC       77.5
ISI         9
temp      8.3
RH         97
wind        4
rain      0.2
area        0
Name: 3, dtype: object

In [5]:
type(df.iloc[3])

pandas.core.series.Series

In [4]:
df.iloc[[3,7,8]]

X  Y month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain  area
3  8  6   mar  fri  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2   0.0
7  8  6   aug  mon  91.5  145.4  608.2  10.7   8.0  86   2.2   0.0   0.0
8  8  6   sep  tue  91.0  129.5  692.6   7.0  13.1  63   5.4   0.0   0.0

In [12]:
df.iloc[:,2]

0      mar
1      oct
2      oct
3      mar
4      mar
5      aug
6      aug
7      aug
8      sep
9      sep
10     sep
11     sep
12     aug
13     sep
14     sep
15     sep
16     mar
17     oct
18     mar
19     apr
20     sep
21     sep
22     jun
23     aug
24     aug
25     aug
26     sep
27     sep
28     sep
29     sep
      ... 
487    aug
488    aug
489    aug
490    aug
491    aug
492    aug
493    aug
494    aug
495    aug
496    aug
497    aug
498    aug
499    aug
500    aug
501    aug
502    aug
503    aug
504    aug
505    aug
506    aug
507    aug
508    aug
509    aug
510    aug
511    aug
512    aug
513    aug
514    aug
515    aug
516    nov
Name: month, Length: 517, dtype: object

In [2]:
import pandas as pd
df = pd.read_csv('https://query.data.world/s/vBDCsoHCytUSLKkLvq851k2b8JOCkF')
df_2 = df.set_index('X', inplace=False)
print(df_2.head())

   Y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area
X                                                                  
7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0
7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0
7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0
8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0
8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0


Sorting Dataframes
Description
Sort the dataframe on 'month' and 'day' in ascending order in the dataframe 'df'

In [3]:
import pandas as pd
df = pd.read_csv('https://query.data.world/s/vBDCsoHCytUSLKkLvq851k2b8JOCkF')
df_2 = df.sort_values(by=['month','day'],ascending=True)
print(df_2.head(20))

     X  Y month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain   area
241  4  4   apr  fri  83.0   23.3   85.3   2.3  16.7  20   3.1   0.0   0.00
442  6  5   apr  mon  87.9   24.9   41.6   3.7  10.9  64   3.1   0.0   3.35
19   6  4   apr  sat  86.3   27.4   97.1   5.1   9.3  44   4.5   0.0   0.00
239  7  5   apr  sun  81.9    3.0    7.9   3.5  13.4  75   1.8   0.0   0.00
469  6  3   apr  sun  91.0   14.6   25.6  12.3  13.7  33   9.4   0.0  61.13
470  5  4   apr  sun  91.0   14.6   25.6  12.3  17.6  27   5.8   0.0   0.00
176  6  5   apr  thu  81.5    9.1   55.2   2.7   5.8  54   5.8   0.0   4.61
196  6  5   apr  thu  81.5    9.1   55.2   2.7   5.8  54   5.8   0.0  10.93
240  6  3   apr  wed  88.0   17.2   43.5   3.8  15.2  51   2.7   0.0   0.00
12   6  5   aug  fri  63.5   70.8  665.3   0.8  17.0  72   6.7   0.0   0.00
78   1  2   aug  fri  90.1  108.0  529.8  12.5  14.7  66   2.7   0.0   0.00
142  8  6   aug  fri  90.1  108.0  529.8  12.5  21.2  51   8.9   0.0   0.61
184  8  6   

In [11]:
a_list = ["word"]
modified_list = a_list*5
print(modified_list)

['word', 'word', 'word', 'word', 'word']


In [12]:
id(a_list), id(modified_list)

(177594998152, 177598197640)

Indexing Dataframes
Description
Print only the even numbers of **rows** of the dataframe 'df'.

Note: Don't include the row indexed zero.

In [2]:
import pandas as pd
df = pd.read_csv('https://query.data.world/s/vBDCsoHCytUSLKkLvq851k2b8JOCkF')
df_2 = df[2::2]
print(df_2.head(20))

    X  Y month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain  area
2   7  4   oct  sat  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0   0.0
4   8  6   mar  sun  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0   0.0
6   8  6   aug  mon  92.3   88.9  495.6   8.5  24.1  27   3.1   0.0   0.0
8   8  6   sep  tue  91.0  129.5  692.6   7.0  13.1  63   5.4   0.0   0.0
10  7  5   sep  sat  92.5   88.0  698.6   7.1  17.8  51   7.2   0.0   0.0
12  6  5   aug  fri  63.5   70.8  665.3   0.8  17.0  72   6.7   0.0   0.0
14  6  5   sep  wed  92.9  133.3  699.6   9.2  26.4  21   4.5   0.0   0.0
16  5  5   mar  sat  91.7   35.8   80.8   7.8  15.1  27   5.4   0.0   0.0
18  6  4   mar  wed  89.2   27.9   70.8   6.3  15.9  35   4.0   0.0   0.0
20  6  4   sep  tue  91.0  129.5  692.6   7.0  18.3  40   2.7   0.0   0.0
22  7  4   jun  sun  94.3   96.3  200.0  56.1  21.0  44   4.5   0.0   0.0
24  7  4   aug  sat  93.5  139.4  594.2  20.3  23.7  32   5.8   0.0   0.0
26  7  4   sep  fri  92.4  117.9  668.

Selecting **Columns** of a Dataframe
Description
Print out the columns 'month', 'day', 'temp', 'area' from the dataframe 'df'.

In [1]:
import pandas as pd
df = pd.read_csv('https://query.data.world/s/vBDCsoHCytUSLKkLvq851k2b8JOCkF')
df_2 = df[['month', 'day' , 'temp' , 'area']]
print(df_2.head(20))

   month  day  temp  area
0    mar  fri   8.2   0.0
1    oct  tue  18.0   0.0
2    oct  sat  14.6   0.0
3    mar  fri   8.3   0.0
4    mar  sun  11.4   0.0
5    aug  sun  22.2   0.0
6    aug  mon  24.1   0.0
7    aug  mon   8.0   0.0
8    sep  tue  13.1   0.0
9    sep  sat  22.8   0.0
10   sep  sat  17.8   0.0
11   sep  sat  19.3   0.0
12   aug  fri  17.0   0.0
13   sep  mon  21.3   0.0
14   sep  wed  26.4   0.0
15   sep  fri  22.9   0.0
16   mar  sat  15.1   0.0
17   oct  mon  16.7   0.0
18   mar  wed  15.9   0.0
19   apr  sat   9.3   0.0


In [2]:
import pandas as pd
df = pd.read_csv('https://query.data.world/s/vBDCsoHCytUSLKkLvq851k2b8JOCkF')
df.head()

X  Y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area
0  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0
1  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0
2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0
3  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0
4  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0

Dataframe iloc
Description
Using iloc index the dataframe to print all the rows of the columns at index 3,4,5.
Hint: Use 3,4,5 not 2,3,4

In [3]:
df2=df.iloc[:,3:6]
df2

day  FFMC    DMC
0    fri  86.2   26.2
1    tue  90.6   35.4
2    sat  90.6   43.7
3    fri  91.7   33.3
4    sun  89.3   51.3
5    sun  92.3   85.3
6    mon  92.3   88.9
7    mon  91.5  145.4
8    tue  91.0  129.5
9    sat  92.5   88.0
10   sat  92.5   88.0
11   sat  92.8   73.2
12   fri  63.5   70.8
13   mon  90.9  126.5
14   wed  92.9  133.3
15   fri  93.3  141.2
16   sat  91.7   35.8
17   mon  84.9   32.8
18   wed  89.2   27.9
19   sat  86.3   27.4
20   tue  91.0  129.5
21   mon  91.8   78.5
22   sun  94.3   96.3
23   sat  90.2  110.9
24   sat  93.5  139.4
25   sun  91.4  142.4
26   fri  92.4  117.9
27   mon  90.9  126.5
28   sat  93.4  145.4
29   sun  93.5  149.3
..   ...   ...    ...
487  tue  95.1  141.3
488  tue  95.1  141.3
489  wed  95.1  141.3
490  wed  95.1  141.3
491  thu  95.8  152.0
492  fri  95.9  158.0
493  fri  95.9  158.0
494  sat  96.0  164.0
495  mon  96.2  175.5
496  mon  96.2  175.5
497  tue  96.1  181.1
498  tue  96.1  181.1
499  tue  96.1  181.1
500  tue  96.1  181.1
501  tue  96.1  181.1
502  tue  96.1  181.1
503  wed  94.5  139.4
504  wed  94.5  139.4
505  thu  91.0  163.2
506  fri  91.0  166.9
507  fri  91.0  166.9
508  fri  91.0  166.9
509  fri  91.0  166.9
510  fri  91.0  166.9
511  sun  81.6   56.7
512  sun  81.6   56.7
513  sun  81.6   56.7
514  sun  81.6   56.7
515  sat  94.4  146.0
516  tue  79.5    3.0

[517 rows x 3 columns]

In [4]:
import pandas as pd
df = pd.read_csv('https://query.data.world/s/vBDCsoHCytUSLKkLvq851k2b8JOCkF')
df_2 = df.iloc[:,[3,4,5]]
print(df_2.head(20))

    day  FFMC    DMC
0   fri  86.2   26.2
1   tue  90.6   35.4
2   sat  90.6   43.7
3   fri  91.7   33.3
4   sun  89.3   51.3
5   sun  92.3   85.3
6   mon  92.3   88.9
7   mon  91.5  145.4
8   tue  91.0  129.5
9   sat  92.5   88.0
10  sat  92.5   88.0
11  sat  92.8   73.2
12  fri  63.5   70.8
13  mon  90.9  126.5
14  wed  92.9  133.3
15  fri  93.3  141.2
16  sat  91.7   35.8
17  mon  84.9   32.8
18  wed  89.2   27.9
19  sat  86.3   27.4


In [14]:
import pandas as pd
df = pd.read_csv('https://query.data.world/s/vBDCsoHCytUSLKkLvq851k2b8JOCkF')
df_2 = df.loc[(df.area>0),:]
print(df_2.head(20))

     X  Y month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain  area
138  9  9   jul  tue  85.8   48.3  313.4   3.9  18.0  42   2.7   0.0  0.36
139  1  4   sep  tue  91.0  129.5  692.6   7.0  21.7  38   2.2   0.0  0.43
140  2  5   sep  mon  90.9  126.5  686.5   7.0  21.9  39   1.8   0.0  0.47
141  1  2   aug  wed  95.5   99.9  513.3  13.2  23.3  31   4.5   0.0  0.55
142  8  6   aug  fri  90.1  108.0  529.8  12.5  21.2  51   8.9   0.0  0.61
143  1  2   jul  sat  90.0   51.3  296.3   8.7  16.6  53   5.4   0.0  0.71
144  2  5   aug  wed  95.5   99.9  513.3  13.2  23.8  32   5.4   0.0  0.77
145  6  5   aug  thu  95.2  131.7  578.8  10.4  27.4  22   4.0   0.0  0.90
146  5  4   mar  mon  90.1   39.7   86.6   6.2  13.2  40   5.4   0.0  0.95
147  8  3   sep  tue  84.4   73.4  671.9   3.2  24.2  28   3.6   0.0  0.96
148  2  2   aug  tue  94.8  108.3  647.1  17.0  17.4  43   6.7   0.0  1.07
149  8  6   sep  thu  93.7   80.9  685.2  17.9  23.7  25   4.5   0.0  1.12
150  6  5   jun  fri  92.

In [13]:
df2=df.loc[df['area']>0,:]
df2

X  Y month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain    area
138  9  9   jul  tue  85.8   48.3  313.4   3.9  18.0  42   2.7   0.0    0.36
139  1  4   sep  tue  91.0  129.5  692.6   7.0  21.7  38   2.2   0.0    0.43
140  2  5   sep  mon  90.9  126.5  686.5   7.0  21.9  39   1.8   0.0    0.47
141  1  2   aug  wed  95.5   99.9  513.3  13.2  23.3  31   4.5   0.0    0.55
142  8  6   aug  fri  90.1  108.0  529.8  12.5  21.2  51   8.9   0.0    0.61
143  1  2   jul  sat  90.0   51.3  296.3   8.7  16.6  53   5.4   0.0    0.71
144  2  5   aug  wed  95.5   99.9  513.3  13.2  23.8  32   5.4   0.0    0.77
145  6  5   aug  thu  95.2  131.7  578.8  10.4  27.4  22   4.0   0.0    0.90
146  5  4   mar  mon  90.1   39.7   86.6   6.2  13.2  40   5.4   0.0    0.95
147  8  3   sep  tue  84.4   73.4  671.9   3.2  24.2  28   3.6   0.0    0.96
148  2  2   aug  tue  94.8  108.3  647.1  17.0  17.4  43   6.7   0.0    1.07
149  8  6   sep  thu  93.7   80.9  685.2  17.9  23.7  25   4.5   0.0    1.12
150  6  5   jun  fri  92.5   56.4  433.3   7.1  23.2  39   5.4   0.0    1.19
151  9  9   jul  sun  90.1   68.6  355.2   7.2  24.8  29   2.2   0.0    1.36
152  3  4   jul  sat  90.1   51.2  424.1   6.2  24.6  43   1.8   0.0    1.43
153  5  4   sep  fri  94.3   85.1  692.3  15.9  20.1  47   4.9   0.0    1.46
154  1  5   sep  sat  93.4  145.4  721.4   8.1  29.6  27   2.7   0.0    1.46
155  7  4   aug  sun  94.8  108.3  647.1  17.0  16.4  47   1.3   0.0    1.56
156  2  4   sep  sat  93.4  145.4  721.4   8.1  28.6  27   2.2   0.0    1.61
157  2  2   aug  wed  92.1  111.2  654.1   9.6  18.4  45   3.6   0.0    1.63
158  2  4   aug  wed  92.1  111.2  654.1   9.6  20.5  35   4.0   0.0    1.64
159  7  4   sep  fri  92.4  117.9  668.0  12.2  19.0  34   5.8   0.0    1.69
160  7  4   mar  mon  90.1   39.7   86.6   6.2  16.1  29   3.1   0.0    1.75
161  6  4   aug  thu  95.2  131.7  578.8  10.4  20.3  41   4.0   0.0    1.90
162  6  3   mar  sat  90.6   50.1  100.4   7.8  15.2  31   8.5   0.0    1.94
163  8  6   sep  sat  92.5  121.1  674.4   8.6  17.8  56   1.8   0.0    1.95
164  8  5   sep  sun  89.7   90.0  704.4   4.8  17.8  67   2.2   0.0    2.01
165  6  5   mar  thu  84.9   18.2   55.0   3.0   5.3  70   4.5   0.0    2.14
166  6  5   aug  wed  92.1  111.2  654.1   9.6  16.6  47   0.9   0.0    2.29
167  6  5   aug  wed  96.0  127.1  570.5  16.5  23.4  33   4.5   0.0    2.51
..  .. ..   ...  ...   ...    ...    ...   ...   ...  ..   ...   ...     ...
471  4  3   may  fri  89.6   25.4   73.7   5.7  18.0  40   4.0   0.0   38.48
472  8  3   jun  mon  88.2   96.2  229.0   4.7  14.3  79   4.0   0.0    1.94
473  9  4   jun  sat  90.5   61.1  252.6   9.4  24.5  50   3.1   0.0   70.32
474  4  3   jun  thu  93.0  103.8  316.7  10.8  26.4  35   2.7   0.0   10.08
475  2  5   jun  thu  93.7  121.7  350.2  18.0  22.7  40   9.4   0.0    3.19
476  4  3   jul  thu  93.5   85.3  395.0   9.9  27.2  28   1.3   0.0    1.76
477  4  3   jul  sun  93.7  101.3  423.4  14.7  26.1  45   4.0   0.0    7.36
478  7  4   jul  sun  93.7  101.3  423.4  14.7  18.2  82   4.5   0.0    2.21
479  7  4   jul  mon  89.2  103.9  431.6   6.4  22.6  57   4.9   0.0  278.53
480  9  9   jul  thu  93.2  114.4  560.0   9.5  30.2  25   4.5   0.0    2.75
482  3  4   aug  sun  94.9  130.3  587.1  14.1  23.4  40   5.8   0.0    1.29
484  2  5   aug  sun  94.9  130.3  587.1  14.1  33.1  25   4.0   0.0   26.43
485  2  4   aug  mon  95.0  135.5  596.3  21.3  30.6  28   3.6   0.0    2.07
486  5  4   aug  tue  95.1  141.3  605.8  17.7  24.1  43   6.3   0.0    2.00
487  5  4   aug  tue  95.1  141.3  605.8  17.7  26.4  34   3.6   0.0   16.40
488  4  4   aug  tue  95.1  141.3  605.8  17.7  19.4  71   7.6   0.0   46.70
493  1  3   aug  fri  95.9  158.0  633.6  11.3  27.5  29   4.5   0.0   43.32
494  6  6   aug  sat  96.0  164.0  643.0  14.0  30.8  30   4.9   0.0    8.59
496  4  5   aug  mon  96.2  175.5  661.8  16.8  32.6  26   3.1   0.0    2.77
497  3  4   aug  tue  96.1  181.1  671.2  14.3  32.3  27   2.2   0.0   14.68
4

Applying Conditions on Dataframes
Description
Print all the columns and the rows where 'area' is greater than 0, 'wind' is greater than 1 and the 'temp' is greater than 15.
Execution Time Limit
15 seconds